# ============================================================
#  POSTGRES POD
#  PostgreSQL is a permanent database (stores data on disk)
#  Votes come here from Redis through the Worker
# ============================================================
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:9.4
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "votes"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
