# ============================================================
#  POSTGRES SERVICE
#  ClusterIP = internal only
#  Name "db" is used by worker and result-app to connect
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
