# ============================================================
#  REDIS POD
#  Redis is an in-memory (RAM) database
#  When a user votes, the vote is stored here first
#  Then the Worker picks it up and saves it to PostgreSQL
# ============================================================
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379
