# ============================================================
#  RESULT APP POD
#  Node.js app that shows voting results
#  Reads from PostgreSQL and displays in browser
# ============================================================
apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    app: result-app
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result:before
      ports:
        - containerPort: 80
