# ============================================================
#  WORKER POD
#  Background service - no UI, no browser access needed
#  Job: Read votes from Redis -> Save them to PostgreSQL
#  Connects to "redis" service and "db" service by name
# ============================================================
apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    app: worker
spec:
  containers:
    - name: worker
      image: dockersamples/examplevotingapp_worker
